encyclopedia/urls.py
from django.urls import path, re_path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("New", views.create, name="create"),
    path("<str:select>", views.index, name="index"),
    path("Edit/<str:select>", views.edit, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
import markdown2
from . import util
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
import random #Used in layout template#
from django.contrib import messages
from django.core.cache import cache

cache.clear()

class busqueda(forms.Form):
    q = forms.CharField(label="Search wiki") 

class new(forms.Form):
    title = forms.CharField(label="Title wiki")
    text = forms.CharField(widget=forms.Textarea)

def index(request, select=None):
    if "search" not in request.session:
        request.session["search"] = []

    context = {
        "entries": util.list_entries(),
        "search_q": busqueda(),
        "search" : request.session["search"],
        "select" : select,
        "see" : None
    }

    entries_l = [entries_l.lower() for entries_l in context['entries']]
    if request.method == "POST":
        search_q = busqueda(request.POST)
        if search_q.is_valid():
            q = search_q.cleaned_data['q']
            request.session["search"] = [q]
            return HttpResponseRedirect(reverse("encyclopedia:index", args=request.session["search"]))
    elif select:
        select_l = select.lower()
        if select_l in entries_l:
            index = entries_l.index(select_l)        
            context["see"] = markdown2.markdown(util.get_entry(context["entries"][index]))
        else:
            lista = []
            for x in entries_l:
                if select_l in x and len(select_l)/len(x) >= 2/3:
                    lista.append(context["entries"][entries_l.index(x)])
            if lista:
                context["entries"] = lista
                context["see"] = 'Search'
        
    return render(request, "encyclopedia/index.html", context)


def create(request):
    context = {'form': new(),
                'entries':util.list_entries(),
                'error':None
    }
    entries_l = [entries_l.lower() for entries_l in context['entries']]
    if request.method == "POST":
        form = new(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            text = form.cleaned_data['text']
            if title.lower() not in entries_l:
                util.save_entry(title, text)
                return HttpResponseRedirect(reverse('encyclopedia:index', kwargs={'select':title}))
            else:
                context["error"] = f"Title '{title}' in use: please change this"

    return render(request, "encyclopedia/create.html", context)

def edit(request, select):
    title = select
    text = util.get_entry(title)
    editor = new({'title':select, 'text':text})
    editor.fields['title'].hidden = False
    editor.fields['title'].disabled = True
    editor.fields['title'].required = False
    entries = util.list_entries()
    entries_l = [entries_l.lower() for entries_l in entries]

    context = {
        'entries':entries,
        'form': editor,
        'select': select
    }

    if request.method == "POST":
        form = new(request.POST)
        form.fields["title"].required = False
        if form.is_valid():
            text_f = form.cleaned_data['text']
            util.save_entry(title, text_f)
            return HttpResponseRedirect(reverse('encyclopedia:index', kwargs={'select':title}))

    return render(request, "encyclopedia/edit.html", context)

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a wiki
{% endblock %}

{% block body %}
    {% if not error %}
    <h1> Create a wiki</h1>
    <form action="{% url 'encyclopedia:create' %}" method="post">{% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Save">
    </form>
    {% else %}
    <h1 style="color:red">ERROR: Bad request</h1>
    <h3>{{ error }}</h3>
    {% endif %}
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit wiki {{select}}
{% endblock %}

{% block body %}
    <h1>Edit wiki "{{ select }}"</h1>
    <form action="{% url 'encyclopedia:edit' select %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {% if not select or see == 'Search' %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:index' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
    {% elif see %}

    {{ see|safe }}
    <a href="{% url 'encyclopedia:edit' select %}">Edit</a>
    {% else %}

    <h1> Not found </h1>

    <h4> The file {{ select }} doesn't exist</h4>

    {% endif %}

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="post">
                    {% csrf_token %}
                    {{ search_q }}
                    <input type="submit" value="Search">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:index' entries|random %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                <div class="border border-primary m-auto p-auto">
                {% block body %}
                {% endblock %}
                </div>
            </div>
        </div>

    </body>
</html>